`default_nettype none

module debug_module_wrapper
  # (
     parameter OUTPUT_WIDTH = 128,
     parameter ADDR_WIDTH = 15
     )
  (

   input		       sys_clk,
   input		       sys_rstn,

   // INSTR stuff
   input		       S_RAM_INSTR_req,
   input		       S_RAM_INSTR_we,
   input [3:0]		       S_RAM_INSTR_be,
   input [31:0]		       S_RAM_INSTR_addr,
   input [31:0]		       S_RAM_INSTR_wr_data,
   input		       S_RAM_INSTR_rd_valid,
   input [31:0]		       S_RAM_INSTR_rd_data,
   input		       S_RAM_INSTR_gnt,

   input		       M_AXI_INSTR_arvalid,
   input		       M_AXI_INSTR_arready,
   input [31:0]		       M_AXI_INSTR_araddr,
   input [2:0]		       M_AXI_INSTR_arsize,
   input [1:0]		       M_AXI_INSTR_arburst,
   input [3:0]		       M_AXI_INSTR_arid,
   input [7:0]		       M_AXI_INSTR_arlen,

   input		       M_AXI_INSTR_rvalid,
   input		       M_AXI_INSTR_rready,
   input		       M_AXI_INSTR_rlast,
   input [31:0]		       M_AXI_INSTR_rdata,
   input [1:0]		       M_AXI_INSTR_rresp,
   input [3:0]		       M_AXI_INSTR_rid,

   // DATA stuff
   input		       S_RAM_DATA_req,
   input		       S_RAM_DATA_we,
   input [3:0]		       S_RAM_DATA_be,
   input [31:0]		       S_RAM_DATA_addr,
   input [31:0]		       S_RAM_DATA_wr_data,
   input		       S_RAM_DATA_rd_valid,
   input [31:0]		       S_RAM_DATA_rd_data,
   input		       S_RAM_DATA_gnt,

   input		       M_AXI_DATA_arvalid,
   input		       M_AXI_DATA_arready,
   input [31:0]		       M_AXI_DATA_araddr,
   input [2:0]		       M_AXI_DATA_arsize,
   input [1:0]		       M_AXI_DATA_arburst,
   input [3:0]		       M_AXI_DATA_arid,
   input [7:0]		       M_AXI_DATA_arlen,

   input		       M_AXI_DATA_rvalid,
   input		       M_AXI_DATA_rready,
   input		       M_AXI_DATA_rlast,
   input [31:0]		       M_AXI_DATA_rdata,
   input [1:0]		       M_AXI_DATA_rresp,
   input [3:0]		       M_AXI_DATA_rid,

   input		       M_AXI_DATA_awvalid,
   input		       M_AXI_DATA_awready,
   input [31:0]		       M_AXI_DATA_awaddr,
   input [2:0]		       M_AXI_DATA_awsize,
   input [1:0]		       M_AXI_DATA_awburst,
   input [3:0]		       M_AXI_DATA_awid,
   input [7:0]		       M_AXI_DATA_awlen,

   input		       M_AXI_DATA_wvalid,
   input		       M_AXI_DATA_wready,
   input		       M_AXI_DATA_wlast,
   input [31:0]		       M_AXI_DATA_wdata,
   input [3:0]		       M_AXI_DATA_wstrb,
   input [3:0]		       M_AXI_DATA_wid,

   input		       M_AXI_DATA_bvalid,
   input		       M_AXI_DATA_bready,
   input [1:0]		       M_AXI_DATA_bresp,
   input [3:0]		       M_AXI_DATA_bid,

   // rvfi stuff
   input		       rvfi_valid,
   input		       rvfi_trap,
   input [ 4:0]		       rvfi_rd_addr,
   input [31:0]		       rvfi_rd_wdata,
   input [31:0]		       rvfi_pc_rdata,
   input [31:0]		       rvfi_ext_pre_mip,
   input [31:0]		       rvfi_ext_post_mip,
   input		       rvfi_ext_nmi,
   input		       rvfi_ext_nmi_int,
   input		       rvfi_ext_debug_req,
   input		       rvfi_ext_rf_wr_suppress,
   input [63:0]		       rvfi_ext_mcycle,
   input [319:0]	       rvfi_ext_mhpmcounters, 
   input [319:0]	       rvfi_ext_mhpmcountersh,
   input		       rvfi_ext_ic_scr_key_valid,
   input                       rvfi_force_stop,
   
   input [255:0]	       rvfi_stream_tdata,
   input		       rvfi_stream_tvalid,
   input		       rvfi_stream_tready,
   input [31:0]		       rvfi_stream_tkeep,
  
   input [71:0]		       rvfi_cmd_tdata,
   input		       rvfi_cmd_tvalid,
   input		       rvfi_cmd_tready,

   input [7:0]		       rvfi_sts_tdata,
   input		       rvfi_sts_tvalid,
   input		       rvfi_sts_tready,

   input [127:0]	       rvfi_csr_stream_tdata,
   input		       rvfi_csr_stream_tvalid,
   input		       rvfi_csr_stream_tready,
   input [15:0]		       rvfi_csr_stream_tkeep,

   input [71:0]		       rvfi_csr_cmd_tdata,
   input		       rvfi_csr_cmd_tvalid,
   input		       rvfi_csr_cmd_tready,

   input [7:0]		       rvfi_csr_sts_tdata,
   input		       rvfi_csr_sts_tvalid,
   input		       rvfi_csr_sts_tready,

   // DEBUG stuff
   output [ADDR_WIDTH-1:0]     DEBUG_addr,
   output		       DEBUG_clk,
   output [OUTPUT_WIDTH-1:0]   DEBUG_wrdata,
   input [OUTPUT_WIDTH-1:0]    DEBUG_rddata,
   output		       DEBUG_en,
   output		       DEBUG_rst,
   output [OUTPUT_WIDTH/8-1:0] DEBUG_we

   );

   debug_module
  # (
     .OUTPUT_WIDTH (OUTPUT_WIDTH),
     .ADDR_WIDTH (ADDR_WIDTH)
     ) u_dm
    (
     .sys_clk (sys_clk),
     .sys_rstn (sys_rstn),
     .S_RAM_INSTR_req (S_RAM_INSTR_req),
     .S_RAM_INSTR_we (S_RAM_INSTR_we),
     .S_RAM_INSTR_be (S_RAM_INSTR_be),
     .S_RAM_INSTR_addr (S_RAM_INSTR_addr),
     .S_RAM_INSTR_wrdata (S_RAM_INSTR_wr_data),
     .S_RAM_INSTR_rdvalid (S_RAM_INSTR_rd_valid),
     .S_RAM_INSTR_rddata (S_RAM_INSTR_rd_data),
     .S_RAM_INSTR_gnt (S_RAM_INSTR_gnt),
     .M_AXI_INSTR_arvalid (M_AXI_INSTR_arvalid),
     .M_AXI_INSTR_arready (M_AXI_INSTR_arready),
     .M_AXI_INSTR_araddr (M_AXI_INSTR_araddr),
     .M_AXI_INSTR_arsize (M_AXI_INSTR_arsize),
     .M_AXI_INSTR_arburst (M_AXI_INSTR_arburst),
     .M_AXI_INSTR_arid (M_AXI_INSTR_arid),
     .M_AXI_INSTR_arlen (M_AXI_INSTR_arlen),
     .M_AXI_INSTR_rvalid (M_AXI_INSTR_rvalid),
     .M_AXI_INSTR_rready (M_AXI_INSTR_rready),
     .M_AXI_INSTR_rlast (M_AXI_INSTR_rlast),
     .M_AXI_INSTR_rdata (M_AXI_INSTR_rdata),
     .M_AXI_INSTR_rresp (M_AXI_INSTR_rresp),
     .M_AXI_INSTR_rid (M_AXI_INSTR_rid),
     .S_RAM_DATA_req (S_RAM_DATA_req),
     .S_RAM_DATA_we (S_RAM_DATA_we),
     .S_RAM_DATA_be (S_RAM_DATA_be),
     .S_RAM_DATA_addr (S_RAM_DATA_addr),
     .S_RAM_DATA_wrdata (S_RAM_DATA_wr_data),
     .S_RAM_DATA_rdvalid (S_RAM_DATA_rd_valid),
     .S_RAM_DATA_rddata (S_RAM_DATA_rd_data),
     .S_RAM_DATA_gnt (S_RAM_DATA_gnt),
     .M_AXI_DATA_arvalid (M_AXI_DATA_arvalid),
     .M_AXI_DATA_arready (M_AXI_DATA_arready),
     .M_AXI_DATA_araddr (M_AXI_DATA_araddr),
     .M_AXI_DATA_arsize (M_AXI_DATA_arsize),
     .M_AXI_DATA_arburst (M_AXI_DATA_arburst),
     .M_AXI_DATA_arid (M_AXI_DATA_arid),
     .M_AXI_DATA_arlen (M_AXI_DATA_arlen),
     .M_AXI_DATA_rvalid (M_AXI_DATA_rvalid),
     .M_AXI_DATA_rready (M_AXI_DATA_rready),
     .M_AXI_DATA_rlast (M_AXI_DATA_rlast),
     .M_AXI_DATA_rdata (M_AXI_DATA_rdata),
     .M_AXI_DATA_rresp (M_AXI_DATA_rresp),
     .M_AXI_DATA_rid (M_AXI_DATA_rid),
     .M_AXI_DATA_awvalid (M_AXI_DATA_awvalid),
     .M_AXI_DATA_awready (M_AXI_DATA_awready),
     .M_AXI_DATA_awaddr (M_AXI_DATA_awaddr),
     .M_AXI_DATA_awsize (M_AXI_DATA_awsize),
     .M_AXI_DATA_awburst (M_AXI_DATA_awburst),
     .M_AXI_DATA_awid (M_AXI_DATA_awid),
     .M_AXI_DATA_awlen (M_AXI_DATA_awlen),
     .M_AXI_DATA_wvalid (M_AXI_DATA_wvalid),
     .M_AXI_DATA_wready (M_AXI_DATA_wready),
     .M_AXI_DATA_wlast (M_AXI_DATA_wlast),
     .M_AXI_DATA_wdata (M_AXI_DATA_wdata),
     .M_AXI_DATA_wstrb (M_AXI_DATA_wstrb),
     .M_AXI_DATA_wid (M_AXI_DATA_wid),
     .M_AXI_DATA_bvalid (M_AXI_DATA_bvalid),
     .M_AXI_DATA_bready (M_AXI_DATA_bready),
     .M_AXI_DATA_bresp (M_AXI_DATA_bresp),
     .M_AXI_DATA_bid (M_AXI_DATA_bid),
     .rvfi_valid (rvfi_valid),
     .rvfi_trap (rvfi_trap),
     .rvfi_rd_addr (rvfi_rd_addr),
     .rvfi_rd_wdata (rvfi_rd_wdata),
     .rvfi_pc_rdata (rvfi_pc_rdata),
     .rvfi_ext_pre_mip (rvfi_ext_pre_mip),
     .rvfi_ext_post_mip (rvfi_ext_post_mip),
     .rvfi_ext_nmi (rvfi_ext_nmi),
     .rvfi_ext_nmi_int (rvfi_ext_nmi_int),
     .rvfi_ext_debug_req (rvfi_ext_debug_req),
     .rvfi_ext_rf_wr_suppress (rvfi_ext_rf_wr_suppress),
     .rvfi_ext_mcycle (rvfi_ext_mcycle),
     .rvfi_ext_mhpmcounters (rvfi_ext_mhpmcounters), 
     .rvfi_ext_mhpmcountersh (rvfi_ext_mhpmcountersh),
     .rvfi_ext_ic_scr_key_valid (rvfi_ext_ic_scr_key_valid),
     .rvfi_stream_tdata (rvfi_stream_tdata),
     .rvfi_stream_tvalid (rvfi_stream_tvalid),
     .rvfi_stream_tready (rvfi_stream_tready),
     .rvfi_stream_tkeep (rvfi_stream_tkeep),
     .rvfi_cmd_tdata (rvfi_cmd_tdata),
     .rvfi_cmd_tvalid (rvfi_cmd_tvalid),
     .rvfi_cmd_tready (rvfi_cmd_tready),
     .rvfi_sts_tdata (rvfi_sts_tdata),
     .rvfi_sts_tvalid (rvfi_sts_tvalid),
     .rvfi_sts_tready (rvfi_sts_tready),
     .rvfi_csr_stream_tdata (rvfi_csr_stream_tdata),
     .rvfi_csr_stream_tvalid (rvfi_csr_stream_tvalid),
     .rvfi_csr_stream_tready (rvfi_csr_stream_tready),
     .rvfi_csr_stream_tkeep (rvfi_csr_stream_tkeep),
     .rvfi_csr_cmd_tdata (rvfi_csr_cmd_tdata),
     .rvfi_csr_cmd_tvalid (rvfi_csr_cmd_tvalid),
     .rvfi_csr_cmd_tready (rvfi_csr_cmd_tready),
     .rvfi_csr_sts_tdata (rvfi_csr_sts_tdata),
     .rvfi_csr_sts_tvalid (rvfi_csr_sts_tvalid),
     .rvfi_csr_sts_tready (rvfi_csr_sts_tready),
     .DEBUG_addr (DEBUG_addr),
     .DEBUG_clk (DEBUG_clk),
     .DEBUG_wrdata (DEBUG_wrdata),
     .DEBUG_rddata (DEBUG_rddata),
     .DEBUG_en (DEBUG_en),
     .DEBUG_rst (DEBUG_rst),
     .DEBUG_we (DEBUG_we)   
     );
   
endmodule
